name: "Wire Pod"
description: "Wire Pod software in a Home Assistant Add-On"
slug: "wire-pod"
url: "https://github.com/CB-42458/Wire-Pod-Home-Assistant-Add-On"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  443/tcp: 443
  8080/tcp: 8080
  80/tcp: 80
  8084/tcp: 8084
map:
  - type: data
    path: /chipper
    read_only: false
  - type: data
    path: /vosk
    read_only: false
image: "ghcr.io/kercre123/wire-pod"
version: "main"
restart: unless-stopped