name: "Wire Pod mDNS"
description: "The Multicast DNS (mDNS) service for Wire Pod"
slug: "wire-pod-mdns"
url: "https://hub.docker.com/r/flungo/avahi"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
host_network: true
init: false
image: "flungo/avahi"
version: "main"
environment:
  SERVER_HOST_NAME: "escapepod"
  SERVER_DOMAIN_NAME: "local"
restart: unless-stopped