name: "Wire Pod mDNS"
description: "The Multicast DNS (mDNS) service for Wire Pod"
slug: "wire-pod-mdns"
url: "https://hub.docker.com/r/flungo/avahi"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
host_network: true
init: false
image: "ghcr.io/kercre123/wire-pod-mdns"
version: "latest"
enviroment:
  - name: "SERVER_HOST_NAME"
    value: "escapepod"
  - name: "SERVER_DOMAIN_NAME"
    value: "local"
