name: "Wire Pod mDNS"
description: "The Multicast DNS (mDNS) service for Wire Pod"
version: "0.1.4"
slug: "wire-pod-mdns"
url: "https://github.com/CB-42458/Wire-Pod-Home-Assistant-Add-On"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
host_network: true
init: false
